# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'default_permissions': (), 'permissions': (('get_content', '查看故障列表'), ('detail_content', '故障详情'), ('add_content', '添加故障'), ('edit_content', '编辑故障'), ('del_content', '删除故障'))},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'default_permissions': (), 'permissions': (('update_type', '更新故障类型'), ('del_type', '删除故障类型'))},
        ),
    ]
